nodeLinker: hoisted
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - '@esbuild/linux-x64'
  - '@esbuild/linux-arm64'
  - '@esbuild/darwin-x64'
  - '@esbuild/darwin-arm64'
  - '@esbuild/win32-x64'
  - '@esbuild/android-arm64'
  - '@esbuild/android-arm'
