/**
 * AUTOPILOT01 English marker bank.
 * Detects craving, trigger exposure, automatic movement toward use,
 * approach bias, attentional bias, and conditioned trigger responses.
 */

export const AUTOPILOT01_MARKERS_EN = {
  autopilotLanguage: [
    "before i knew it",
    "automatically",
    "on autopilot",
    "i was already there",
    "i was already on my way",
    "my legs carried me",
    "i was already driving there",
    "i was already walking there",
    "without thinking",
    "before i realized",
    "i only noticed when",
    "it happened by itself",
    "my body did it",
    "i couldn't stop",
    "i was already doing it",
    "the route",
    "same route",
    "always the same way",
    "i went that way again",
  ],
  triggerExposure: [
    "the store",
    "past the liquor store",
    "past the dealer",
    "the shelf",
    "the bottle",
    "the smell",
    "i saw it",
    "i smelled it",
    "someone was using",
    "someone was drinking",
    "money in my pocket",
    "just got paid",
    "home alone",
    "nobody home",
    "friday night",
    "after work",
    "stress at work",
    "had a fight",
    "lonely",
    "alone",
    "bored",
    "nothing to do",
  ],
  approachBias: [
    "i was drawn to it",
    "i felt the pull",
    "i wanted to go there",
    "my body wanted",
    "i couldn't look away",
    "it attracted me",
    "i had to go there",
    "i couldn't help it",
    "the urge was too strong",
    "i was pulled to the store",
    "i wanted to buy",
    "i wanted to score",
  ],
  attentionalBias: [
    "i could only think about",
    "i could only see",
    "everything reminded me of",
    "i couldn't stop thinking",
    "it was the only thing in my head",
    "tunnel",
    "tunnel vision",
    "i only saw the bottle",
    "i only saw the shelf",
    "my attention kept going there",
    "i couldn't concentrate",
    "it kept coming back",
  ],
  conditionedTrigger: [
    "every time",
    "always when i",
    "as soon as i",
    "when i'm stressed",
    "when i'm alone",
    "when i feel ashamed",
    "when i get angry",
    "when i'm sad",
    "after a fight",
    "after work",
    "on friday",
    "on the weekend",
    "when i have money",
    "when i see that place",
    "when i see that person",
    "my body reacts",
    "my body already knows",
    "it's a habit",
    "it's a pattern",
  ],
};

export const AUTOPILOT01_MARKER_IDS_EN = {
  autopilotLanguage: "en_autopilot_language",
  triggerExposure: "en_trigger_exposure",
  approachBias: "en_approach_bias",
  attentionalBias: "en_attentional_bias",
  conditionedTrigger: "en_conditioned_trigger",
};
