/**
 * CLINICAL CONTEXT RELEVANCE SELECTOR
 * 
 * Deterministic client-side selector that uses nano themes to determine
 * which schemas/modes are relevant for the current message.
 * 
 * Rules:
 * - Engine decides, GPT formulates.
 * - If user asks directly about schemas/modes → ALL are sent.
 * - Otherwise → only theme-relevant schemas/modes are sent.
 * - If no theme match → send all (safe fallback, no data loss).
 */

// ── THEME → SCHEMA RELEVANCE MAP ──────────────────────────────────────────
// Maps nano themes to relevant schema identifiers.
// Based on schema therapy (Young et al.) domain groupings.
// Coverage: all 397 Elias themes + Kim themes mapped to 16 schemas.
const THEME_TO_SCHEMAS: Record<string, string[]> = {
  // ─── ABANDONMENT / INSTABILITY ───────────────────────────────────────
  abandonment_fear: ['abandonment', 'emotional_deprivation'],
  they_always_leave: ['abandonment', 'mistrust_abuse'],
  relational_alarm: ['abandonment', 'emotional_deprivation'],
  attachment_alarm: ['abandonment', 'enmeshment'],
  closeness_panic: ['abandonment', 'vulnerability'],
  trust_rupture: ['mistrust_abuse', 'abandonment'],
  betrayal_expectation: ['mistrust_abuse', 'abandonment'],
  fear_of_being_left: ['abandonment'],
  attachment_panic: ['abandonment', 'vulnerability'],
  relational_freeze: ['abandonment', 'emotional_inhibition'],
  intimacy_shutdown: ['abandonment', 'emotional_inhibition'],
  proximity_trigger: ['abandonment', 'vulnerability'],
  nobody_can_be_trusted: ['mistrust_abuse'],
  all_bonds_break: ['mistrust_abuse', 'abandonment'],
  attachment_mistrust: ['mistrust_abuse', 'abandonment'],
  repeated_rejection: ['abandonment', 'defectiveness_shame'],
  never_chosen: ['abandonment', 'defectiveness_shame'],
  second_choice_schema: ['abandonment', 'defectiveness_shame'],
  rejection_repetition: ['abandonment', 'defectiveness_shame'],
  not_chosen_wound: ['abandonment', 'defectiveness_shame'],
  fear_of_closeness: ['abandonment', 'emotional_inhibition'],
  connection_ambivalence: ['abandonment', 'enmeshment'],
  ambivalent_closeness: ['abandonment', 'enmeshment'],
  proximity_ambivalence: ['abandonment', 'enmeshment'],
  want_connection_too_much: ['abandonment', 'emotional_deprivation'],
  closeness_overload: ['abandonment', 'enmeshment'],
  push_pull_contact: ['abandonment', 'enmeshment'],
  distance_after_closeness: ['abandonment', 'emotional_inhibition'],
  post_connection_shutdown: ['abandonment', 'emotional_inhibition'],
  vulnerability_aftershock: ['abandonment', 'emotional_inhibition'],
  intimacy_hangover: ['abandonment', 'emotional_inhibition'],
  closeness_then_withdrawal: ['abandonment', 'emotional_inhibition'],
  intimacy_as_danger: ['abandonment', 'mistrust_abuse'],
  engulfment_fear: ['enmeshment', 'abandonment'],
  autonomy_threat: ['enmeshment', 'dependence_incompetence'],
  closeness_as_control: ['mistrust_abuse', 'enmeshment'],
  relational_fusion_fear: ['enmeshment', 'abandonment'],
  
  // ─── MISTRUST / ABUSE ───────────────────────────────────────────────
  gaslighting: ['mistrust_abuse'],
  reality_distortion: ['mistrust_abuse'],
  gaslighting_possible: ['mistrust_abuse'],
  betrayal_discovery_shock: ['mistrust_abuse', 'abandonment'],
  trust_repair: ['mistrust_abuse'],
  sexual_trauma: ['mistrust_abuse', 'vulnerability'],
  body_shame: ['mistrust_abuse', 'defectiveness_shame'],
  feeling_dirty: ['mistrust_abuse', 'defectiveness_shame'],
  touch_trigger: ['mistrust_abuse', 'vulnerability'],
  sexual_boundary_violation: ['mistrust_abuse'],
  trauma_body_memory: ['mistrust_abuse', 'vulnerability'],
  boundary_violation_normalized: ['mistrust_abuse', 'subjugation'],
  it_belongs: ['mistrust_abuse', 'subjugation'],
  normalized_harm: ['mistrust_abuse', 'subjugation'],
  learned_tolerance_of_harm: ['mistrust_abuse', 'subjugation'],
  relational_domination: ['mistrust_abuse', 'subjugation'],
  
  // ─── EMOTIONAL DEPRIVATION ──────────────────────────────────────────
  emotional_overwhelm: ['emotional_deprivation', 'vulnerability'],
  cant_handle_feelings: ['emotional_deprivation', 'vulnerability'],
  falling_apart: ['emotional_deprivation', 'vulnerability'],
  invisibility: ['emotional_deprivation', 'defectiveness_shame'],
  nobody_sees_me: ['emotional_deprivation'],
  unseen_pain: ['emotional_deprivation'],
  emotional_invisibility: ['emotional_deprivation'],
  disappearing_self: ['emotional_deprivation', 'defectiveness_shame'],
  coregulation_failure: ['emotional_deprivation'],
  nobody_calms_me: ['emotional_deprivation'],
  unreachable_state: ['emotional_deprivation'],
  support_does_not_land: ['emotional_deprivation'],
  too_much_for_others: ['emotional_deprivation', 'defectiveness_shame'],
  structural_loneliness: ['emotional_deprivation', 'abandonment'],
  no_real_connection: ['emotional_deprivation', 'abandonment'],
  nobody_would_miss_me: ['emotional_deprivation', 'defectiveness_shame'],
  social_disconnection: ['emotional_deprivation'],
  existential_isolation: ['emotional_deprivation'],
  loneliness_to_use: ['emotional_deprivation', 'insufficient_self_control'],
  use_to_not_feel_loneliness: ['emotional_deprivation', 'insufficient_self_control'],
  isolation_craving: ['emotional_deprivation', 'insufficient_self_control'],
  absence_pain: ['emotional_deprivation', 'abandonment'],
  connection_void_relapse: ['emotional_deprivation', 'insufficient_self_control'],
  
  // ─── DEFECTIVENESS / SHAME ──────────────────────────────────────────
  self_hatred: ['defectiveness_shame', 'punitiveness'],
  shame: ['defectiveness_shame'],
  guilt: ['defectiveness_shame', 'self_sacrifice'],
  self_criticism: ['defectiveness_shame', 'punitiveness'],
  worthlessness: ['defectiveness_shame', 'dependence_incompetence'],
  failure_identity: ['defectiveness_shame', 'unrelenting_standards'],
  existence_shame: ['defectiveness_shame'],
  vulnerability_shame: ['defectiveness_shame', 'emotional_inhibition'],
  rejection_shame: ['defectiveness_shame', 'abandonment'],
  self_disgust: ['defectiveness_shame'],
  abandonment_shame: ['defectiveness_shame', 'abandonment'],
  relational_shame: ['defectiveness_shame', 'abandonment'],
  identity_attack_after_rejection: ['defectiveness_shame', 'abandonment'],
  internalized_rejection: ['defectiveness_shame'],
  defectiveness_schema: ['defectiveness_shame'],
  not_worth_recovery: ['defectiveness_shame'],
  no_place_in_world: ['defectiveness_shame', 'emotional_deprivation'],
  global_failure: ['defectiveness_shame'],
  shame_fusion: ['defectiveness_shame'],
  learned_failure: ['defectiveness_shame', 'negativity_pessimism'],
  all_or_nothing_failure: ['defectiveness_shame', 'unrelenting_standards'],
  never_should_have_been_born: ['defectiveness_shame'],
  not_allowed_to_exist: ['defectiveness_shame'],
  burden_identity: ['defectiveness_shame', 'self_sacrifice'],
  no_right_to_exist: ['defectiveness_shame'],
  redundant_self: ['defectiveness_shame'],
  existence_worthlessness: ['defectiveness_shame'],
  relapse_guilt: ['defectiveness_shame', 'insufficient_self_control'],
  post_relapse_shame: ['defectiveness_shame', 'insufficient_self_control'],
  ruined_everything: ['defectiveness_shame'],
  all_or_nothing_after_relapse: ['defectiveness_shame', 'insufficient_self_control'],
  relapse_identity_fusion: ['defectiveness_shame', 'insufficient_self_control'],
  starting_from_zero: ['defectiveness_shame', 'negativity_pessimism'],
  relapse_reset_belief: ['defectiveness_shame', 'negativity_pessimism'],
  all_progress_lost: ['defectiveness_shame', 'negativity_pessimism'],
  streak_broken_shame: ['defectiveness_shame'],
  restart_hopelessness: ['defectiveness_shame', 'negativity_pessimism'],
  guilt_without_reason: ['defectiveness_shame'],
  free_floating_guilt: ['defectiveness_shame'],
  suspected_innocence: ['defectiveness_shame'],
  chronic_guilt: ['defectiveness_shame'],
  guilt_for_existing: ['defectiveness_shame'],
  relationship_as_mirror: ['defectiveness_shame', 'approval_seeking'],
  self_image_through_other: ['defectiveness_shame', 'approval_seeking'],
  reflected_shame: ['defectiveness_shame'],
  externalized_self_worth: ['defectiveness_shame', 'approval_seeking'],
  relational_self_disgust: ['defectiveness_shame'],
  
  // ─── DEPENDENCE / INCOMPETENCE ─────────────────────────────────────
  seeking_to_be_carried: ['dependence_incompetence', 'enmeshment'],
  regressive_dependency: ['dependence_incompetence'],
  help_refusal: ['dependence_incompetence', 'emotional_inhibition'],
  maternal_longing: ['dependence_incompetence', 'emotional_deprivation'],
  unmet_mother_need: ['dependence_incompetence', 'emotional_deprivation'],
  rescue_attachment: ['dependence_incompetence', 'abandonment'],
  mother_complex: ['dependence_incompetence', 'enmeshment'],
  autonomous_but_exhausted: ['dependence_incompetence', 'self_sacrifice'],
  doing_everything_alone: ['dependence_incompetence', 'emotional_deprivation'],
  exhausted_independence: ['dependence_incompetence'],
  isolated_self_reliance: ['dependence_incompetence', 'emotional_deprivation'],
  help_guilt: ['dependence_incompetence', 'defectiveness_shame'],
  burden_shame: ['dependence_incompetence', 'defectiveness_shame'],
  afraid_to_ask_help: ['dependence_incompetence', 'defectiveness_shame'],
  support_request_block: ['dependence_incompetence'],
  not_want_to_be_burden: ['dependence_incompetence', 'defectiveness_shame'],
  
  // ─── VULNERABILITY ─────────────────────────────────────────────────
  anxiety: ['vulnerability'],
  panic: ['vulnerability'],
  panic_without_trigger: ['vulnerability'],
  body_alarm: ['vulnerability'],
  somatic_panic: ['vulnerability'],
  unexplained_anxiety: ['vulnerability'],
  autonomic_activation: ['vulnerability'],
  racing_thoughts: ['vulnerability'],
  hypervigilance: ['vulnerability', 'mistrust_abuse'],
  constant_scanning: ['vulnerability', 'mistrust_abuse'],
  never_relaxed: ['vulnerability'],
  threat_monitoring: ['vulnerability', 'mistrust_abuse'],
  social_scanning: ['vulnerability', 'mistrust_abuse'],
  body_alarm_monitoring: ['vulnerability'],
  emotional_instability: ['vulnerability', 'insufficient_self_control'],
  rapid_state_shift: ['vulnerability'],
  affective_swing: ['vulnerability'],
  emotional_whiplash: ['vulnerability'],
  unstable_self_state: ['vulnerability'],
  overload: ['vulnerability'],
  explosion_risk: ['vulnerability', 'insufficient_self_control'],
  too_much_at_once: ['vulnerability'],
  acute_pressure: ['vulnerability'],
  overstimulation: ['vulnerability'],
  emotional_overload: ['vulnerability'],
  social_overload: ['vulnerability'],
  too_many_people: ['vulnerability'],
  proximity_overload: ['vulnerability', 'enmeshment'],
  
  // ─── ENMESHMENT ────────────────────────────────────────────────────
  parental_symbiosis: ['enmeshment', 'dependence_incompetence'],
  enmeshment: ['enmeshment'],
  still_their_child: ['enmeshment'],
  parental_guilt: ['enmeshment', 'self_sacrifice'],
  adult_child_role: ['enmeshment', 'dependence_incompetence'],
  differentiation_issue: ['enmeshment'],
  caregiver_identity_in_dependent: ['enmeshment', 'self_sacrifice'],
  relational_control_loss: ['enmeshment', 'subjugation'],
  what_is_mine: ['enmeshment'],
  boundary_confusion: ['enmeshment', 'subjugation'],
  emotional_fusion: ['enmeshment'],
  relational_enmeshment: ['enmeshment'],
  relationship_regression: ['enmeshment', 'dependence_incompetence'],
  becoming_small: ['enmeshment', 'subjugation'],
  child_state_in_relationship: ['enmeshment', 'dependence_incompetence'],
  adult_position_loss: ['enmeshment'],
  attachment_regression: ['enmeshment', 'dependence_incompetence'],
  
  // ─── SUBJUGATION ───────────────────────────────────────────────────
  overresponsibility: ['subjugation', 'self_sacrifice'],
  carrying_others: ['subjugation', 'self_sacrifice'],
  responsibility_fusion: ['subjugation', 'enmeshment'],
  
  // ─── SELF-SACRIFICE ────────────────────────────────────────────────
  self_sacrifice: ['self_sacrifice', 'subjugation'],
  parentification: ['self_sacrifice', 'enmeshment'],
  child_had_to_be_strong: ['self_sacrifice', 'enmeshment'],
  early_burden: ['self_sacrifice'],
  forced_maturity: ['self_sacrifice'],
  childhood_overresponsibility: ['self_sacrifice', 'enmeshment'],
  
  // ─── UNRELENTING STANDARDS ─────────────────────────────────────────
  perfection_as_survival: ['unrelenting_standards', 'punitiveness'],
  no_mistakes_allowed: ['unrelenting_standards'],
  overcontrol: ['unrelenting_standards', 'emotional_inhibition'],
  rigid_recovery: ['unrelenting_standards'],
  perfectionism: ['unrelenting_standards'],
  internal_pressure: ['unrelenting_standards'],
  never_enough: ['unrelenting_standards', 'defectiveness_shame'],
  all_or_nothing_recovery: ['unrelenting_standards'],
  punitive_self_control: ['unrelenting_standards', 'punitiveness'],
  perfectionistic_control: ['unrelenting_standards'],
  control_as_survival: ['unrelenting_standards', 'vulnerability'],
  fear_of_losing_control: ['unrelenting_standards', 'vulnerability'],
  fear_of_error: ['unrelenting_standards'],
  punitive_perfectionism: ['unrelenting_standards', 'punitiveness'],
  mistake_danger: ['unrelenting_standards'],
  failing_despite_effort: ['unrelenting_standards', 'defectiveness_shame'],
  effort_without_worth: ['unrelenting_standards', 'defectiveness_shame'],
  chronic_inadequacy: ['unrelenting_standards', 'defectiveness_shame'],
  proving_self: ['unrelenting_standards', 'approval_seeking'],
  
  // ─── INSUFFICIENT SELF-CONTROL ─────────────────────────────────────
  craving: ['insufficient_self_control'],
  substance_urge: ['insufficient_self_control'],
  using_desire: ['insufficient_self_control'],
  uncontrollable_urge: ['insufficient_self_control'],
  impulse_discharge: ['insufficient_self_control'],
  explosive_impulse: ['insufficient_self_control'],
  no_brake: ['insufficient_self_control'],
  act_before_thinking: ['insufficient_self_control'],
  urge_to_act: ['insufficient_self_control'],
  habit_loop: ['insufficient_self_control'],
  automatic_use: ['insufficient_self_control'],
  without_thinking: ['insufficient_self_control'],
  cue_response: ['insufficient_self_control'],
  autopilot_relapse: ['insufficient_self_control'],
  preconscious_use: ['insufficient_self_control'],
  boredom_craving: ['insufficient_self_control'],
  emptiness_trigger: ['insufficient_self_control', 'emotional_deprivation'],
  underarousal: ['insufficient_self_control'],
  nothing_to_feel: ['insufficient_self_control', 'emotional_deprivation'],
  anhedonia_craving: ['insufficient_self_control'],
  habit_craving: ['insufficient_self_control'],
  self_medication: ['insufficient_self_control', 'emotional_deprivation'],
  use_to_calm: ['insufficient_self_control'],
  inner_restlessness: ['insufficient_self_control', 'vulnerability'],
  sedation_seeking: ['insufficient_self_control'],
  medication_misuse_risk: ['insufficient_self_control'],
  wish_for_numbness: ['insufficient_self_control', 'emotional_inhibition'],
  do_not_want_to_feel: ['insufficient_self_control', 'emotional_inhibition'],
  sedation_wish: ['insufficient_self_control'],
  emotional_shutdown: ['insufficient_self_control', 'emotional_inhibition'],
  numbing_urge: ['insufficient_self_control'],
  escape_feeling: ['insufficient_self_control'],
  repeated_relapse_context: ['insufficient_self_control'],
  cannot_maintain_recovery: ['insufficient_self_control', 'defectiveness_shame'],
  relapse_loop: ['insufficient_self_control'],
  context_defeats_plan: ['insufficient_self_control'],
  recurring_trigger_pattern: ['insufficient_self_control'],
  relapse_trigger: ['insufficient_self_control'],
  used_again: ['insufficient_self_control', 'defectiveness_shame'],
  slipped: ['insufficient_self_control'],
  prevention: ['insufficient_self_control'],
  loss_of_control: ['insufficient_self_control', 'vulnerability'],
  masking_relapse: ['insufficient_self_control', 'emotional_inhibition'],
  pretending_fine: ['insufficient_self_control', 'emotional_inhibition'],
  hidden_use: ['insufficient_self_control'],
  relapse_secrecy: ['insufficient_self_control'],
  minimization: ['insufficient_self_control'],
  concealed_craving: ['insufficient_self_control'],
  
  // ─── APPROVAL SEEKING ──────────────────────────────────────────────
  approval_seeking: ['approval_seeking'],
  fear_of_being_seen: ['approval_seeking', 'defectiveness_shame'],
  fear_of_exposure: ['approval_seeking', 'defectiveness_shame'],
  shame_mask: ['approval_seeking', 'defectiveness_shame'],
  imposter_self: ['approval_seeking', 'defectiveness_shame'],
  being_seen_through: ['approval_seeking', 'defectiveness_shame'],
  exposure_panic: ['approval_seeking', 'vulnerability'],
  social_masking: ['approval_seeking', 'emotional_inhibition'],
  everyone_thinks_im_fine: ['approval_seeking', 'emotional_inhibition'],
  hidden_distress: ['approval_seeking', 'emotional_inhibition'],
  functional_collapse: ['approval_seeking'],
  outside_inside_gap: ['approval_seeking', 'emotional_inhibition'],
  
  // ─── NEGATIVITY / PESSIMISM ────────────────────────────────────────
  expectation_of_failure: ['negativity_pessimism'],
  pessimistic_prediction: ['negativity_pessimism'],
  failure_forecast: ['negativity_pessimism'],
  learned_helplessness: ['negativity_pessimism', 'defectiveness_shame'],
  preemptive_defeat: ['negativity_pessimism'],
  existential_void: ['negativity_pessimism', 'emotional_deprivation'],
  is_this_all: ['negativity_pessimism'],
  meaninglessness: ['negativity_pessimism'],
  recovery_emptiness: ['negativity_pessimism'],
  future_void: ['negativity_pessimism'],
  existential_black_hole: ['negativity_pessimism', 'emotional_deprivation'],
  disappearance_fantasy: ['negativity_pessimism', 'defectiveness_shame'],
  
  // ─── EMOTIONAL INHIBITION ──────────────────────────────────────────
  emotional_masking: ['emotional_inhibition'],
  cheerful_mask: ['emotional_inhibition'],
  laughing_but_empty: ['emotional_inhibition'],
  humor_defense: ['emotional_inhibition'],
  affective_flatness: ['emotional_inhibition'],
  social_performance: ['emotional_inhibition', 'approval_seeking'],
  crying_equals_weakness: ['emotional_inhibition', 'defectiveness_shame'],
  self_attack_after_emotion: ['emotional_inhibition', 'punitiveness'],
  emotional_exposure_shame: ['emotional_inhibition', 'defectiveness_shame'],
  shame_after_crying: ['emotional_inhibition', 'defectiveness_shame'],
  cognitive_escape: ['emotional_inhibition'],
  living_in_head: ['emotional_inhibition'],
  overanalysis: ['emotional_inhibition'],
  rumination_as_avoidance: ['emotional_inhibition'],
  intellectualization: ['emotional_inhibition'],
  body_disconnection: ['emotional_inhibition'],
  fear_of_reflection: ['emotional_inhibition'],
  self_reflection_avoidance: ['emotional_inhibition'],
  introspection_threat: ['emotional_inhibition'],
  do_not_want_to_look: ['emotional_inhibition'],
  reflection_shutdown: ['emotional_inhibition'],
  
  
  // ─── OTHER / MULTI-DOMAIN ──────────────────────────────────────────
  permanent_outsider: ['emotional_deprivation', 'defectiveness_shame'],
  nowhere_belonging: ['emotional_deprivation', 'defectiveness_shame'],
  outsider_identity: ['emotional_deprivation', 'defectiveness_shame'],
  not_part_of_anything: ['emotional_deprivation'],
  social_alienation: ['emotional_deprivation'],
  chronically_misunderstood: ['emotional_deprivation'],
  not_getting_me: ['emotional_deprivation'],
  invalidation: ['emotional_deprivation', 'mistrust_abuse'],
  defensive_exhaustion: ['emotional_deprivation'],
  misread_identity: ['emotional_deprivation', 'defectiveness_shame'],
  system_rejection: ['defectiveness_shame', 'emotional_deprivation'],
  not_fit_system: ['defectiveness_shame'],
  societal_mismatch: ['defectiveness_shame'],
  institutional_shame: ['defectiveness_shame'],
  isolation_as_safety: ['emotional_inhibition', 'abandonment'],
  protective_withdrawal: ['emotional_inhibition'],
  self_protection_isolation: ['emotional_inhibition'],
  avoidant_retreat: ['emotional_inhibition'],
  unsafe_connection: ['mistrust_abuse', 'abandonment'],
  relationship_pattern_repetition: ['abandonment', 'mistrust_abuse'],
  new_relationship_old_pattern: ['abandonment'],
  repetition_compulsion: ['abandonment'],
  relational_trigger: ['abandonment'],
  pattern_returning: ['abandonment'],
  identity_confusion_under_pressure: ['vulnerability', 'enmeshment'],
  yelling_trigger: ['vulnerability', 'mistrust_abuse'],
  self_loss_under_conflict: ['vulnerability', 'enmeshment'],
  pressure_collapse: ['vulnerability'],
  leave_me_alone: ['emotional_inhibition'],
  autonomous_defense: ['emotional_inhibition', 'dependence_incompetence'],
  support_rejection: ['dependence_incompetence', 'emotional_inhibition'],
  help_shame: ['dependence_incompetence', 'defectiveness_shame'],
  defensive_independence: ['dependence_incompetence', 'emotional_inhibition'],
  spiritual_loss: ['emotional_deprivation'],
  lost_connection: ['emotional_deprivation'],
  meaning_loss: ['emotional_deprivation', 'negativity_pessimism'],
  existential_disconnection: ['emotional_deprivation', 'negativity_pessimism'],
  faith_rupture: ['emotional_deprivation'],
  loss_of_belonging_to_life: ['emotional_deprivation', 'negativity_pessimism'],
  childhood_trauma: ['vulnerability', 'mistrust_abuse'],
  old_alarm: ['vulnerability'],
  inner_child_activation: ['vulnerability'],
  early_schema_trigger: ['vulnerability'],
  past_present_overlap: ['vulnerability'],
  parental_loss: ['abandonment', 'emotional_deprivation'],
  unfinished_grief: ['abandonment', 'emotional_deprivation'],
  grief_guilt: ['abandonment', 'defectiveness_shame'],
  mother_loss: ['abandonment', 'emotional_deprivation'],
  father_loss: ['abandonment', 'emotional_deprivation'],
  unresolved_bereavement: ['abandonment', 'emotional_deprivation'],
  confrontation_trigger: ['vulnerability', 'mistrust_abuse'],
  
  // ─── THEMES THAT DON'T MAP TO SPECIFIC SCHEMAS (general/neutral) ──
  // These map to specific schemas where clinically relevant:
  willpower_blame: ['insufficient_self_control'],
  feeling_weak: ['insufficient_self_control', 'defectiveness_shame'],
  discipline_failure: ['insufficient_self_control'],
  automatic_trigger: ['insufficient_self_control'],
  conditioned_response: ['insufficient_self_control'],
  sleep_disturbance: ['vulnerability'],
  use_to_sleep: ['insufficient_self_control', 'vulnerability'],
  night_craving: ['insufficient_self_control'],
  insomnia_risk: ['vulnerability'],
  circadian_disruption: ['vulnerability'],
  suicidal_language_possible: ['vulnerability', 'defectiveness_shame'],
  generational_patterns: ['enmeshment', 'self_sacrifice'],
  
  // These get 'all' by default via the no_match fallback
  // greeting, small_talk, general_question, grounding, purpose, motivation,
  // goals, hope, meaning, concentration, foggy_mind, scattered, acceptance,
  // struggle_with_control, resistance, self_discovery, psychoeducation, etc.

  // ─── KIM-SPECIFIC THEMES ───────────────────────────────────────────
  // Caregiver burden / self-loss domain
  loneliness: ['emotional_deprivation', 'abandonment'],
  isolation: ['emotional_deprivation'],
  no_connections: ['emotional_deprivation', 'abandonment'],
  broken_trust: ['mistrust_abuse', 'abandonment'],
  betrayal: ['mistrust_abuse'],
  intimacy_panic: ['abandonment', 'vulnerability'],
  pushing_away: ['abandonment', 'emotional_inhibition'],
  sleep_problems: ['vulnerability'],
  insomnia: ['vulnerability'],
  nightmares: ['vulnerability', 'mistrust_abuse'],
  fear_of_failure: ['unrelenting_standards', 'defectiveness_shame'],
  loss: ['abandonment', 'emotional_deprivation'],
  death: ['abandonment', 'emotional_deprivation'],
  grief: ['abandonment', 'emotional_deprivation'],
  mourning: ['abandonment', 'emotional_deprivation'],
  overwhelm: ['vulnerability'],
  exhaustion: ['vulnerability', 'self_sacrifice'],
  burnout: ['self_sacrifice', 'vulnerability'],
  explosion: ['vulnerability', 'insufficient_self_control'],
  abuse: ['mistrust_abuse'],
  traumatic_memories: ['mistrust_abuse', 'vulnerability'],
  shame_from_rejection: ['defectiveness_shame', 'abandonment'],
  being_rejected: ['abandonment', 'defectiveness_shame'],
  feeling_unlovable: ['defectiveness_shame', 'abandonment'],
  fear_of_proximity: ['abandonment', 'emotional_inhibition'],
  loss_of_control_after_confrontation: ['vulnerability', 'insufficient_self_control'],
  responsibility_for_others: ['self_sacrifice', 'subjugation'],
  guilt_after_relapse: ['defectiveness_shame', 'insufficient_self_control'],
  repetition_of_rejection: ['abandonment', 'defectiveness_shame'],
  failure_as_identity: ['defectiveness_shame'],
  penance_for_existing: ['defectiveness_shame'],
  craving_from_boredom: ['insufficient_self_control'],
  child_must_be_strong: ['self_sacrifice', 'enmeshment'],
  mask_of_happiness: ['emotional_inhibition'],
  symbiosis_with_parent: ['enmeshment', 'dependence_incompetence'],
  self_hate_at_vulnerability: ['defectiveness_shame', 'emotional_inhibition'],
  panic_without_cause: ['vulnerability'],
  fear_of_recognition: ['approval_seeking', 'defectiveness_shame'],
  co_regulation_fails: ['emotional_deprivation'],
  societal_rejection: ['defectiveness_shame', 'emotional_deprivation'],
  new_relationships_as_repetition: ['abandonment'],
  refusal_of_help: ['dependence_incompetence', 'emotional_inhibition'],
  relationship_equals_regression: ['enmeshment', 'dependence_incompetence'],
  loss_of_spirituality: ['emotional_deprivation'],
  guilt_asking_for_help: ['dependence_incompetence', 'defectiveness_shame'],
  fleeing_into_thoughts: ['emotional_inhibition'],
  social_expectation_vs_reality: ['approval_seeking', 'emotional_inhibition'],
  loss_of_control_in_relationship: ['enmeshment', 'subjugation'],
  desire_for_numbness: ['insufficient_self_control', 'emotional_inhibition'],
  automatism_of_use: ['insufficient_self_control'],
  starting_over_again: ['defectiveness_shame', 'negativity_pessimism'],
  innocence_suspected: ['defectiveness_shame'],
  boundary_violation_as_norm: ['mistrust_abuse', 'subjugation'],
  deep_ambivalence: ['abandonment', 'enmeshment'],
  
  // Kim caregiver-specific themes
  parentification_pattern: ['self_sacrifice', 'enmeshment'],
  had_to_care_for_parents: ['self_sacrifice', 'enmeshment'],
  no_childhood: ['self_sacrifice', 'emotional_deprivation'],
  forced_adult_role: ['self_sacrifice', 'enmeshment'],
  child_as_caregiver: ['self_sacrifice', 'enmeshment'],
  financial_dependency: ['dependence_incompetence', 'subjugation'],
  money_as_control: ['mistrust_abuse', 'subjugation'],
  no_financial_autonomy: ['dependence_incompetence', 'subjugation'],
  economic_abuse: ['mistrust_abuse', 'subjugation'],
  financial_control: ['mistrust_abuse', 'subjugation'],
  ambiguous_loss: ['abandonment', 'emotional_deprivation'],
  living_grief: ['abandonment', 'emotional_deprivation'],
  missing_who_they_were: ['abandonment', 'emotional_deprivation'],
  social_isolation_caregiver: ['emotional_deprivation', 'self_sacrifice'],
  lost_own_contacts: ['emotional_deprivation', 'self_sacrifice'],
  caregiving_isolation: ['emotional_deprivation', 'self_sacrifice'],
  medical_concern_partner: ['vulnerability', 'self_sacrifice'],
  withdrawal_symptoms: ['vulnerability'],
  organ_damage_concern: ['vulnerability'],
  rescue_role: ['self_sacrifice', 'enmeshment'],
  controlling_other_recovery: ['self_sacrifice', 'enmeshment'],
  managing_other_sobriety: ['self_sacrifice', 'enmeshment'],
  intent_attribution: ['mistrust_abuse'],
  motive_assumption: ['mistrust_abuse'],
  deliberate_harm_belief: ['mistrust_abuse'],
  emotional_dependency: ['dependence_incompetence', 'enmeshment'],
  self_loss_through_other: ['enmeshment', 'subjugation'],
  day_depends_on_other: ['dependence_incompetence', 'enmeshment'],
};

// ── THEME → MODE RELEVANCE MAP ──────────────────────────────────────────
const THEME_TO_MODES: Record<string, string[]> = {
  // ─── VULNERABLE CHILD ──────────────────────────────────────────────
  emotional_overwhelm: ['vulnerable_child'],
  cant_handle_feelings: ['vulnerable_child'],
  falling_apart: ['vulnerable_child'],
  abandonment_fear: ['vulnerable_child'],
  they_always_leave: ['vulnerable_child'],
  unseen_pain: ['vulnerable_child'],
  invisibility: ['vulnerable_child'],
  nobody_sees_me: ['vulnerable_child'],
  anxiety: ['vulnerable_child'],
  panic: ['vulnerable_child'],
  panic_without_trigger: ['vulnerable_child'],
  body_alarm: ['vulnerable_child'],
  existence_shame: ['vulnerable_child'],
  seeking_to_be_carried: ['vulnerable_child'],
  fear_of_being_left: ['vulnerable_child'],
  attachment_panic: ['vulnerable_child'],
  nobody_calms_me: ['vulnerable_child'],
  unreachable_state: ['vulnerable_child'],
  support_does_not_land: ['vulnerable_child'],
  structural_loneliness: ['vulnerable_child'],
  no_real_connection: ['vulnerable_child'],
  nobody_would_miss_me: ['vulnerable_child'],
  loneliness_to_use: ['vulnerable_child', 'impulsive_child'],
  absence_pain: ['vulnerable_child'],
  maternal_longing: ['vulnerable_child'],
  unmet_mother_need: ['vulnerable_child'],
  childhood_trauma: ['vulnerable_child'],
  old_alarm: ['vulnerable_child'],
  inner_child_activation: ['vulnerable_child'],
  early_schema_trigger: ['vulnerable_child'],
  past_present_overlap: ['vulnerable_child'],
  parental_loss: ['vulnerable_child'],
  mother_loss: ['vulnerable_child'],
  father_loss: ['vulnerable_child'],
  becoming_small: ['vulnerable_child'],
  child_state_in_relationship: ['vulnerable_child'],
  attachment_regression: ['vulnerable_child'],
  relationship_regression: ['vulnerable_child'],
  
  // ─── ANGRY CHILD ──────────────────────────────────────────────────
  confrontation_trigger: ['angry_child'],
  shame_rage: ['angry_child'],
  explosive_response: ['angry_child'],
  criticism_reactivity: ['angry_child'],
  yelling_trigger: ['angry_child'],
  explosion_risk: ['angry_child'],
  identity_attack_after_rejection: ['angry_child'],
  relational_domination: ['angry_child'],
  
  // ─── IMPULSIVE CHILD ───────────────────────────────────────────────
  craving: ['impulsive_child'],
  substance_urge: ['impulsive_child'],
  using_desire: ['impulsive_child'],
  uncontrollable_urge: ['impulsive_child'],
  impulse_discharge: ['impulsive_child'],
  explosive_impulse: ['impulsive_child'],
  no_brake: ['impulsive_child'],
  act_before_thinking: ['impulsive_child'],
  urge_to_act: ['impulsive_child'],
  boredom_craving: ['impulsive_child'],
  habit_craving: ['impulsive_child'],
  anhedonia_craving: ['impulsive_child'],
  automatic_use: ['impulsive_child'],
  without_thinking: ['impulsive_child'],
  cue_response: ['impulsive_child'],
  autopilot_relapse: ['impulsive_child'],
  preconscious_use: ['impulsive_child'],
  loss_of_control: ['impulsive_child'],
  
  // ─── COMPLIANT SURRENDER ───────────────────────────────────────────
  overresponsibility: ['compliant_surrender'],
  carrying_others: ['compliant_surrender'],
  self_sacrifice: ['compliant_surrender'],
  parentification: ['compliant_surrender'],
  child_had_to_be_strong: ['compliant_surrender'],
  early_burden: ['compliant_surrender'],
  forced_maturity: ['compliant_surrender'],
  childhood_overresponsibility: ['compliant_surrender'],
  boundary_violation_normalized: ['compliant_surrender'],
  normalized_harm: ['compliant_surrender'],
  learned_tolerance_of_harm: ['compliant_surrender'],
  
  // ─── DETACHED PROTECTOR ────────────────────────────────────────────
  distance_after_closeness: ['detached_protector'],
  emotional_masking: ['detached_protector'],
  cheerful_mask: ['detached_protector'],
  closeness_panic: ['detached_protector'],
  protective_withdrawal: ['detached_protector'],
  isolation_as_safety: ['detached_protector'],
  self_medication: ['detached_protector', 'impulsive_child'],
  use_to_calm: ['detached_protector', 'impulsive_child'],
  wish_for_numbness: ['detached_protector'],
  do_not_want_to_feel: ['detached_protector'],
  sedation_wish: ['detached_protector'],
  emotional_shutdown: ['detached_protector'],
  numbing_urge: ['detached_protector'],
  escape_feeling: ['detached_protector'],
  cognitive_escape: ['detached_protector'],
  living_in_head: ['detached_protector'],
  intellectualization: ['detached_protector'],
  body_disconnection: ['detached_protector'],
  fear_of_reflection: ['detached_protector'],
  self_reflection_avoidance: ['detached_protector'],
  introspection_threat: ['detached_protector'],
  do_not_want_to_look: ['detached_protector'],
  reflection_shutdown: ['detached_protector'],
  social_masking: ['detached_protector'],
  everyone_thinks_im_fine: ['detached_protector'],
  hidden_distress: ['detached_protector'],
  outside_inside_gap: ['detached_protector'],
  masking_relapse: ['detached_protector'],
  pretending_fine: ['detached_protector'],
  hidden_use: ['detached_protector'],
  relapse_secrecy: ['detached_protector'],
  avoidant_retreat: ['detached_protector'],
  self_protection_isolation: ['detached_protector'],
  leave_me_alone: ['detached_protector'],
  autonomous_defense: ['detached_protector'],
  support_rejection: ['detached_protector'],
  defensive_independence: ['detached_protector'],
  post_connection_shutdown: ['detached_protector'],
  closeness_then_withdrawal: ['detached_protector'],
  intimacy_hangover: ['detached_protector'],
  vulnerability_aftershock: ['detached_protector'],
  laughing_but_empty: ['detached_protector'],
  humor_defense: ['detached_protector'],
  affective_flatness: ['detached_protector'],
  
  // ─── OVERCONTROLLER ────────────────────────────────────────────────
  overcontrol: ['overcontroller'],
  perfection_as_survival: ['overcontroller'],
  rigid_recovery: ['overcontroller'],
  no_mistakes_allowed: ['overcontroller'],
  perfectionism: ['overcontroller'],
  perfectionistic_control: ['overcontroller'],
  control_as_survival: ['overcontroller'],
  fear_of_losing_control: ['overcontroller'],
  all_or_nothing_recovery: ['overcontroller'],
  punitive_self_control: ['overcontroller', 'punitive_parent'],
  overanalysis: ['overcontroller'],
  rumination_as_avoidance: ['overcontroller'],
  hypervigilance: ['overcontroller'],
  constant_scanning: ['overcontroller'],
  never_relaxed: ['overcontroller'],
  threat_monitoring: ['overcontroller'],
  
  // ─── PUNITIVE PARENT ───────────────────────────────────────────────
  self_hatred: ['punitive_parent'],
  self_criticism: ['punitive_parent'],
  punitive_perfectionism: ['punitive_parent'],
  self_attack_after_emotion: ['punitive_parent'],
  self_disgust: ['punitive_parent'],
  relational_self_disgust: ['punitive_parent'],
  guilt_for_existing: ['punitive_parent'],
  
  // ─── DEMANDING PARENT ──────────────────────────────────────────────
  internal_pressure: ['demanding_parent'],
  never_enough: ['demanding_parent'],
  fear_of_error: ['demanding_parent'],
  mistake_danger: ['demanding_parent'],
  proving_self: ['demanding_parent'],
  chronic_inadequacy: ['demanding_parent'],
  
  // ─── HEALTHY ADULT ─────────────────────────────────────────────────
  purpose: ['healthy_adult'],
  motivation: ['healthy_adult'],
  goals: ['healthy_adult'],
  hope: ['healthy_adult'],
  meaning: ['healthy_adult'],
  self_acceptance: ['healthy_adult'],
  acceptance: ['healthy_adult'],
  self_discovery: ['healthy_adult'],
  trust_repair: ['healthy_adult'],
  guilt_forgiveness: ['healthy_adult'],
  worthiness_of_recovery: ['healthy_adult'],

  // ─── KIM-SPECIFIC MODE MAPPINGS ────────────────────────────────────
  loneliness: ['vulnerable_child'],
  isolation: ['vulnerable_child', 'detached_protector'],
  broken_trust: ['vulnerable_child'],
  betrayal: ['vulnerable_child', 'angry_child'],
  intimacy_panic: ['vulnerable_child', 'detached_protector'],
  pushing_away: ['detached_protector'],
  grief: ['vulnerable_child'],
  mourning: ['vulnerable_child'],
  loss: ['vulnerable_child'],
  death: ['vulnerable_child'],
  exhaustion: ['compliant_surrender'],
  burnout: ['compliant_surrender'],
  responsibility_for_others: ['compliant_surrender'],
  child_must_be_strong: ['compliant_surrender', 'vulnerable_child'],
  mask_of_happiness: ['detached_protector'],
  symbiosis_with_parent: ['compliant_surrender', 'vulnerable_child'],
  rescue_role: ['compliant_surrender'],
  controlling_other_recovery: ['overcontroller'],
  managing_other_sobriety: ['overcontroller'],
  self_loss_through_other: ['compliant_surrender', 'vulnerable_child'],
  day_depends_on_other: ['vulnerable_child'],
  emotional_dependency: ['vulnerable_child'],
  parentification_pattern: ['compliant_surrender'],
  had_to_care_for_parents: ['compliant_surrender', 'vulnerable_child'],
  forced_adult_role: ['compliant_surrender'],
  child_as_caregiver: ['compliant_surrender', 'vulnerable_child'],
  caregiving_isolation: ['vulnerable_child', 'detached_protector'],
  social_isolation_caregiver: ['vulnerable_child'],
  ambiguous_loss: ['vulnerable_child'],
  living_grief: ['vulnerable_child'],
  missing_who_they_were: ['vulnerable_child'],
  financial_dependency: ['vulnerable_child', 'compliant_surrender'],
  economic_abuse: ['vulnerable_child'],
  deliberate_harm_belief: ['angry_child'],
  intent_attribution: ['angry_child'],
};

// ── DIRECT QUESTION DETECTION ──────────────────────────────────────────
// Keywords that indicate the user is asking about their schemas/modes directly
const DIRECT_SCHEMA_MODE_KEYWORDS = [
  'schema', 'schemas', 'modus', 'modi', 'mode', 'modes',
  'mijn schema', 'mijn modi', 'mijn modus', 'welke schema',
  'welke modi', 'wat zijn mijn', 'my schemas', 'my modes',
];

export interface RelevanceSelection {
  /** Which schemas are relevant for this message */
  relevantSchemas: string[] | 'all';
  /** Which modes are relevant for this message */
  relevantModes: string[] | 'all';
  /** Why this selection was made */
  reason: 'direct_question_all' | 'theme_matched' | 'no_match_send_all' | 'informational_all' | 'k05_boundary_direct';
  /** Matched themes that drove the selection */
  matchedThemes: string[];
}

/**
 * Determine which schemas/modes are relevant based on nano themes and user intent.
 * 
 * Rules:
 * 1. Direct question about schemas/modes → ALL
 * 2. Intent=informational + self_discovery theme → ALL
 * 3. Theme match found → only matched schemas/modes
 * 4. No theme match → ALL (safe fallback)
 */
export function selectRelevantClinicalContext(
  nanoThemes: string[],
  nanoIntent: string | undefined,
  userMessage: string,
): RelevanceSelection {
  const msgLower = userMessage.toLowerCase();

  if (/\b(?:zijn\s+plan\s+(?:moet\s+)?trekken|trek\s+je\s+plan|ik\s+ben\s+er\s+klaar\s+mee|i(?:'| a)m\s+done)\b/i.test(userMessage)) {
    return { relevantSchemas: [], relevantModes: [], reason: 'k05_boundary_direct', matchedThemes: ['boundary_statement'] };
  }
  
  // 1. Direct question detection
  const isDirectQuestion = DIRECT_SCHEMA_MODE_KEYWORDS.some(kw => msgLower.includes(kw));
  if (isDirectQuestion) {
    return { relevantSchemas: 'all', relevantModes: 'all', reason: 'direct_question_all', matchedThemes: [] };
  }
  
  // 2. Informational intent + self_discovery
  if (nanoIntent === 'informational' && nanoThemes.includes('self_discovery')) {
    return { relevantSchemas: 'all', relevantModes: 'all', reason: 'informational_all', matchedThemes: ['self_discovery'] };
  }
  
  // 3. Theme-based selection
  const matchedSchemas = new Set<string>();
  const matchedModes = new Set<string>();
  const matchedThemes: string[] = [];
  
  for (const theme of nanoThemes) {
    if (THEME_TO_SCHEMAS[theme]) {
      THEME_TO_SCHEMAS[theme].forEach(s => matchedSchemas.add(s));
      matchedThemes.push(theme);
    }
    if (THEME_TO_MODES[theme]) {
      THEME_TO_MODES[theme].forEach(m => matchedModes.add(m));
      if (!matchedThemes.includes(theme)) matchedThemes.push(theme);
    }
  }
  
  // If we found relevant schemas/modes, return only those
  if (matchedSchemas.size > 0 || matchedModes.size > 0) {
    return {
      relevantSchemas: matchedSchemas.size > 0 ? Array.from(matchedSchemas) : 'all',
      relevantModes: matchedModes.size > 0 ? Array.from(matchedModes) : 'all',
      reason: 'theme_matched',
      matchedThemes,
    };
  }
  
  // 4. No match → send all (safe fallback, never lose data)
  return { relevantSchemas: 'all', relevantModes: 'all', reason: 'no_match_send_all', matchedThemes: [] };
}
