/**
 * AUTOPILOT01 Dutch marker bank.
 * Detects craving, trigger exposure, automatic movement toward use,
 * approach bias, attentional bias, and conditioned trigger responses.
 */

export const AUTOPILOT01_MARKERS_NL = {
  autopilotLanguage: [
    "voor ik het wist",
    "automatisch",
    "automatische piloot",
    "op de automatische piloot",
    "ik stond er al",
    "ik was al onderweg",
    "mijn benen brachten me",
    "ik reed er al naartoe",
    "ik liep er al naartoe",
    "zonder na te denken",
    "voor ik het doorhad",
    "ik merkte het pas toen",
    "het ging vanzelf",
    "mijn lichaam deed het",
    "ik kon niet stoppen",
    "ik was al bezig",
    "de route",
    "dezelfde route",
    "altijd dezelfde weg",
    "ik ging weer die kant op",
  ],
  triggerExposure: [
    "de winkel",
    "langs de slijterij",
    "langs de coffeeshop",
    "langs de dealer",
    "het rek",
    "de fles",
    "de geur",
    "ik zag het staan",
    "ik rook het",
    "iemand gebruikte",
    "iemand dronk",
    "geld op zak",
    "net betaald gekregen",
    "alleen thuis",
    "niemand thuis",
    "vrijdagavond",
    "na het werk",
    "stress op werk",
    "ruzie gehad",
    "eenzaam",
    "alleen",
    "verveling",
    "niks te doen",
  ],
  approachBias: [
    "ik werd ernaar toe getrokken",
    "ik voelde de trek",
    "ik wilde erheen",
    "mijn lichaam wilde",
    "ik kon niet wegkijken",
    "het trok me aan",
    "ik moest erheen",
    "ik kon niet anders",
    "de drang was te sterk",
    "ik werd naar de winkel getrokken",
    "ik wilde kopen",
    "ik wilde scoren",
  ],
  attentionalBias: [
    "ik kon alleen maar denken aan",
    "ik zag alleen maar",
    "alles deed me denken aan",
    "ik kon niet stoppen met denken",
    "het was het enige in mijn hoofd",
    "tunnel",
    "tunnelvisie",
    "ik zag alleen de fles",
    "ik zag alleen het rek",
    "mijn aandacht ging er steeds naartoe",
    "ik kon me niet concentreren",
    "het bleef maar terugkomen",
  ],
  conditionedTrigger: [
    "elke keer als",
    "altijd als ik",
    "zodra ik",
    "als ik stress heb",
    "als ik alleen ben",
    "als ik me schaam",
    "als ik boos word",
    "als ik verdrietig ben",
    "na een ruzie",
    "na werk",
    "op vrijdag",
    "in het weekend",
    "als ik geld heb",
    "als ik die plek zie",
    "als ik die persoon zie",
    "mijn lichaam reageert",
    "mijn lichaam weet het al",
    "het is een gewoonte",
    "het is een patroon",
  ],
};

export const AUTOPILOT01_MARKER_IDS_NL = {
  autopilotLanguage: "nl_autopilot_language",
  triggerExposure: "nl_trigger_exposure",
  approachBias: "nl_approach_bias",
  attentionalBias: "nl_attentional_bias",
  conditionedTrigger: "nl_conditioned_trigger",
};
